<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="A. Onofri, H-P. Piepho and M. Kozak" />


<title>Example 3. Potato starch grains assessed in size categories</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">agriCensData</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Example1.html">Example 1</a>
</li>
<li>
  <a href="Example2.html">Example 2</a>
</li>
<li>
  <a href="Example3.html">Example 3</a>
</li>
<li>
  <a href="RandomEffects.html">Random effects</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Example 3. Potato starch grains assessed in size categories</h1>
<h4 class="author"><em>A. Onofri, H-P. Piepho and M. Kozak</em></h4>

</div>


<hr />
<div id="the-dataset" class="section level1">
<h1>The dataset</h1>
<p>This dataset refers to an experiment which aimed to compare diameters of starch grains from tubers of two potato producers. Starch grains were sampled from tubers collected from the production fields of the producers. The dataset shows the counts of starch grains assigned to one of five diameter classes (&lt;4, [4-8[, [8-12[, [12-16[, <span class="math inline">\(\ge16\)</span> <span class="math inline">\(\mu m\)</span>). For each producer, the diameters were measured from twelve photos taken with a microscope.</p>
<p>The original dataset is in a grouped form; one record represents a photo (12 photos per each producer) and shows the number of starch grains in each of the 5 diameter classes. The producer is indicated in the <code>Group</code> column. The dataset in this form is available in the <code>agriCensData</code> package, which can be installed from gitHub (see <a href="https://onofriandreapg.github.io/agriCensData/index.html">here</a>).</p>
<pre class="r"><code>library(tidyr)
library(nnet)
library(emmeans)
library(survival)
library(agriCensData)

data(starchGrain)
head(starchGrain, 10)</code></pre>
<pre><code>##    Group Photo c1 c2 c3 c4 c5
## 1     P1     1 21 42 40 29 14
## 2     P1     2 23 45 22 12 10
## 3     P1     3 17 40 33 18  8
## 4     P1     4 24 42 30  8  3
## 5     P1     5 19 16 15  8  3
## 6     P1     6 13  7 11  4 10
## 7     P1     7 34 16  8  5  9
## 8     P1     8 23 13 10  4  1
## 9     P1     9 21 28 26  8  8
## 10    P1    10 26 27 27 14  8</code></pre>
<hr />
</div>
<div id="an-unordered-multinomial-logit-model" class="section level1">
<h1>An unordered multinomial logit model</h1>
<p>The grouped nature of the data suggests we should analyse counts. For each photo, all starch grains should be included in one and only one class, so that the proportions of seeds in the five classes should sum up to one.</p>
<p>Therefore, it’s reasonable to consider a multinomial logit model, which treats the classes as nominal categories. In simple terms, a multinomial logit model considers the proportions of grains in each class and how these proportions are affected by the producer. Since such an analysis does not require any assumptions about the real diameter size and its distribution within the population, the method is non-parametric.</p>
<p>In order to fit a multinomial logit model in R, it is useful to reorganise the above dataset into an ungrouped form, so that we have one line for each starch grain (so, 2441 lines), containing all its information: the photo where it was counted, the class to which it was assigned, and the limits of the class (<code>sizeLow</code> and <code>sizeUp</code>). This reordering can be done using the facilities provided in the <code>tidyr</code> package <span class="citation">(Wickham and Henry 2018)</span>.</p>
<pre class="r"><code>moltenData &lt;- gather(starchGrain, variable, value, -Group, -Photo)
datasetR &lt;- moltenData[rep(seq_len(nrow(moltenData)), 
                           moltenData$value), ][, 1:3]
names(datasetR)[3] &lt;- &quot;Class&quot;
row.names(datasetR) &lt;- 1:2441
rm(moltenData)

#Imputing the diameter interval for each starch grain
datasetR$sizeLow = with(datasetR, 
                        ifelse(Class == &quot;c1&quot;, NA,
                               ifelse(Class == &quot;c2&quot;, 4,
                                      ifelse(Class == &quot;c3&quot;, 8, 
                                             ifelse(Class == &quot;c4&quot;, 12, 16))))
                        )

datasetR$sizeUp = with(datasetR, 
                       ifelse(Class == &quot;c1&quot;, 4,
                              ifelse(Class == &quot;c2&quot;, 8,
                                     ifelse(Class == &quot;c3&quot;, 12, 
                                            ifelse(Class == &quot;c4&quot;, 16, NA))))
                       )

head(datasetR, 10)</code></pre>
<pre><code>##    Group Photo Class sizeLow sizeUp
## 1     P1     1    c1      NA      4
## 2     P1     1    c1      NA      4
## 3     P1     1    c1      NA      4
## 4     P1     1    c1      NA      4
## 5     P1     1    c1      NA      4
## 6     P1     1    c1      NA      4
## 7     P1     1    c1      NA      4
## 8     P1     1    c1      NA      4
## 9     P1     1    c1      NA      4
## 10    P1     1    c1      NA      4</code></pre>
<p>Now we can fit a multinomial model, using the <code>multinom()</code> function in the <code>nnet</code> package <span class="citation">(Venables et al. 2002)</span>. The proportions of grains in the five classes for the two producers can be retreived by the multinomial fit with the <code>emmeans()</code> function, which we used in the previous examples.</p>
<pre class="r"><code>mmod &lt;- multinom(Class ~ Group, datasetR)</code></pre>
<pre><code>## # weights:  15 (8 variable)
## initial  value 3928.637944 
## iter  10 value 3802.578106
## final  value 3799.566316 
## converged</code></pre>
<p>In order to test the overall significance of the producer effect, we can fit a null model (which does not include this effect) and compare it with the previous model, using a likelihood ratio test.</p>
<pre class="r"><code>mmodNull &lt;- multinom(Class ~ 1, datasetR)</code></pre>
<pre><code>## # weights:  10 (4 variable)
## initial  value 3928.637944 
## final  value 3825.598726 
## converged</code></pre>
<pre class="r"><code>anova(mmod, mmodNull)</code></pre>
<pre><code>## Likelihood ratio tests of Multinomial Models
## 
## Response: Class
##   Model Resid. df Resid. Dev   Test    Df LR stat.      Pr(Chi)
## 1     1      9760   7651.197                                   
## 2 Group      9756   7599.133 1 vs 2     4 52.06482 1.337066e-10</code></pre>
<p>The difference between the producers is significant (<em>P</em> = 1.34e-10). Therefore, we can try to compare the proportions in each class for the two producers. We can do it with the <code>emmeans()</code> function, which we can also use to test the difference between the producers (here, for each class).</p>
<pre class="r"><code>props &lt;- emmeans(mmod, ~ Group | Class)
props</code></pre>
<pre><code>## Class = c1:
##  Group       prob          SE df   lower.CL  upper.CL
##  P1    0.26387376 0.013294604  8 0.23321635 0.2945312
##  P2    0.26005662 0.011974488  8 0.23244341 0.2876698
## 
## Class = c2:
##  Group       prob          SE df   lower.CL  upper.CL
##  P1    0.29117490 0.013704010  8 0.25957340 0.3227764
##  P2    0.21907767 0.011290852  8 0.19304092 0.2451144
## 
## Class = c3:
##  Group       prob          SE df   lower.CL  upper.CL
##  P1    0.24112576 0.012903510  8 0.21137022 0.2708813
##  P2    0.20640863 0.011048063  8 0.18093176 0.2318855
## 
## Class = c4:
##  Group       prob          SE df   lower.CL  upper.CL
##  P1    0.12102033 0.009838293  8 0.09833319 0.1437075
##  P2    0.15052247 0.009761136  8 0.12801325 0.1730317
## 
## Class = c5:
##  Group       prob          SE df   lower.CL  upper.CL
##  P1    0.08280524 0.008313059  8 0.06363529 0.1019752
##  P2    0.16393459 0.010105997  8 0.14063012 0.1872391
## 
## Confidence level used: 0.95</code></pre>
<pre class="r"><code>CLD(props, Letters = letters)</code></pre>
<pre><code>## Class = c1:
##  Group       prob          SE df   lower.CL  upper.CL .group
##  P2    0.26005662 0.011974488  8 0.23244341 0.2876698  a    
##  P1    0.26387376 0.013294604  8 0.23321635 0.2945312  a    
## 
## Class = c2:
##  Group       prob          SE df   lower.CL  upper.CL .group
##  P2    0.21907767 0.011290852  8 0.19304092 0.2451144  a    
##  P1    0.29117490 0.013704010  8 0.25957340 0.3227764   b   
## 
## Class = c3:
##  Group       prob          SE df   lower.CL  upper.CL .group
##  P2    0.20640863 0.011048063  8 0.18093176 0.2318855  a    
##  P1    0.24112576 0.012903510  8 0.21137022 0.2708813  a    
## 
## Class = c4:
##  Group       prob          SE df   lower.CL  upper.CL .group
##  P1    0.12102033 0.009838293  8 0.09833319 0.1437075  a    
##  P2    0.15052247 0.009761136  8 0.12801325 0.1730317  a    
## 
## Class = c5:
##  Group       prob          SE df   lower.CL  upper.CL .group
##  P1    0.08280524 0.008313059  8 0.06363529 0.1019752  a    
##  P2    0.16393459 0.010105997  8 0.14063012 0.1872391   b   
## 
## Confidence level used: 0.95 
## significance level used: alpha = 0.05</code></pre>
<p>We see that the producer P1 grew tubers with higher proportions of starch grains in the 5th class and lower in the 2nd.</p>
<p>Although not wrong, this unordered multinomial fit is sub-optimal for several reasons:</p>
<ol style="list-style-type: decimal">
<li>It is not parsimonious. Indeed, we needed to estimate eight parameters (four proportions per producer, since the fifth one follows from those four estimated). As we will show later, it is possible to fit a meaningful model also with fewer parameters.</li>
<li>Indirectly, we demonstrated that the second producer had starch grains of smaller size, although we could not calculate several important statistics, such as the mean diameters for the two producers or the diameter variance. This is because we treated the classes as nominal, neglecting that they had natural ordering and distances.</li>
<li>We neglected that starch grains were clustered within photos, meaning that they were stochastically dependent.</li>
</ol>
<hr />
</div>
<div id="a-survival-model-fit" class="section level1">
<h1>A survival model fit</h1>
<p>We should recognise that, for each starch grain, we indeed measured the diameter, though with low precision. So, we failed to obtain a value, but instead we obtained an interval. To take into accout the data collection process, we should model such intervals instead of the corresponding counts.</p>
<p>We can do this by using a survival model, assuming that the distribution of starch grain diameters in the population is Gaussian. As in the other examples, we can use the <code>survreg</code> function in the survival package <span class="citation">(Therneau 1999)</span>.</p>
<pre class="r"><code>surv.reg1 &lt;- survreg(Surv(sizeLow, sizeUp, type = &quot;interval2&quot;) ~ Group,
                     dist = &quot;gaussian&quot;, data = datasetR)
summary(surv.reg1)</code></pre>
<pre><code>## 
## Call:
## survreg(formula = Surv(sizeLow, sizeUp, type = &quot;interval2&quot;) ~ 
##     Group, data = datasetR, dist = &quot;gaussian&quot;)
##              Value Std. Error     z       p
## (Intercept) 7.3398     0.2122 34.59 &lt; 2e-16
## GroupP2     1.3267     0.2853  4.65 3.3e-06
## Log(scale)  1.8909     0.0206 91.68 &lt; 2e-16
## 
## Scale= 6.63 
## 
## Gaussian distribution
## Loglik(model)= -3824.4   Loglik(intercept only)= -3835.2
##  Chisq= 21.57 on 1 degrees of freedom, p= 3.4e-06 
## Number of Newton-Raphson Iterations: 3 
## n= 2441</code></pre>
<p>We now see that the producer P1 had starch grains with an average diameter of 7.34 <span class="math inline">\(\mu m\)</span>, and that the difference between P1 and P2 was 1.33 <span class="math inline">\(\mu m\)</span>, which was significantly different from 0 (<em>P</em> = 3.3e-06).</p>
<p>We argue that the results of this survival model fit are much clearer than those of the multinomial fit, and that, with this second fit, we have better respected the way the data were collected. We discuss these aspects of the analysis in our paper (<em>Literature reference, when available</em>).</p>
<p>Do note, however, that our survival model is still not fully OK, because it disregards the point 3 above: we are still neglecting that starch grains are clustered within photos, which means that they are not independent. We will show how to deal with this aspect in the next webpage.</p>
<hr />
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-therneau_package_1999">
<p><span style="font-variant: small-caps;">Therneau, T</span> (1999) <em>A Package for Survival Analysis in S</em>. R package version 2.36-14, Survival</p>
</div>
<div id="ref-venables2002_Modernappliedstatisticsa">
<p><span style="font-variant: small-caps;">Venables, WN, BD Ripley, WN Venables</span> (2002) <em>Modern applied statistics with S</em>4th ed. Springer, New York</p>
</div>
<div id="ref-tidyr">
<p><span style="font-variant: small-caps;">Wickham, H, L Henry</span> (2018) <em>Tidyr: Easily tidy data with ’spread()’ and ’gather()’ functions</em></p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
