---
title: 'Analyzing interval-censored data in agricultural research: a tutorial'
author: 
  - name: Andrea Onofri
    affiliation: Department of Agriculture, Food and Environmental Sciences, University of Perugia, Borgo XX Giugno 74, 06121 Perugia, Italy, andrea.onofri@unipg.it
  - name: Hans-Peter Piepho
    affiliation: Biostatistics Unit, Institute of Crop Science, University of Hohenheim, Fruwirthstr. 23, 70593 Stuttgart, Germany, hans-peter.piepho@uni-hohenheim.de
  - name: Marcin Kozak
    affiliation: Department of Botany, Warsaw University of Life Sciences - SGGW, Nowoursynowska 159, 02-776 Warsaw, Poland, nyggus@gmail.com
output: 
  html_document:
    toc: yes
    toc_float: 
     collapsed: false
     smooth_scroll: false
bibliography: GroupedData.bib
csl: weed-research.csl
---

---

#Introduction

We have recently written a paper titled "Analyzing interval-censored data in agricultural research: a review with examples and code snippets" (Annals of Applied biology, 174, 3-13; [doi.org/10.1111/aab.12477](https://doi.org/10.1111/aab.12477) ). In that paper we noted that *survival analysis* has mostly been overlooked in agricultural research. This is not because censored data are not found in agriculture. Indeed, a survey of literature in agronomy and related disciplines shows several examples where individual traits cannot be measured with high precision. Their values need to be represented by uncertainty intervals into which the real values fall. Therefore, these measures are censored. Here are some examples we mention in the paper: 

1. time-to-event data (flowering times, germination times)
2. measurements taken with instruments with low resolution or an upper/lower limit of detection
3. counts of organisms which are recorded as higher than a certain threshold value
4. visual measurements on a conventional rating scale (e.g. when scoring pesticide efficacy/phytotoxicity, leaf damage, plant growth, disease severity...)

Unfortunately, when dealing with these data, agricultural researchers usually do not choose appropriate methods of data analysis, but they keep on using conventional tools, such as ANOVA and regression, which are either wrong or inefficient.

  In the paper we give three examples and try to show why it is important to use methods that fully respect the manner in which the data were collected. We also give some software tips to show the real life of analysing censored data, hoping that it will make censored data methods slightly more popular among biologists and agricultural scientists. However, the reviewers suggested we needed some extra space to take the readers hand-by-hand and guide them through the process of data analysis with censored data. Thankful for this suggestion, we offer this tour. 

This webpage aims to provide the commented R code and the datasets to reproduce all the analyses and results described in the main paper [@onofri2019_Analysingcensoreddata]. We also give some extra hints, to open up other possibilities, not considered in the paper. Our hope is that, whenever censored data are recognised, the correct techniques are used more extensively. 

#The package

This web-site is associated to the R package `agriCensData`, which contains all the datasets. You can install it from gitHub. You also need to have installed the *devtools* package. The code is as follows:

```{r results='hide', message=F}
# install.packages("devtools")
#library(devtools)
#install_github("OnofriAndreaPG/agriCensData")
```

# References



