---
title: 'Analyzing interval-censored data in agricultural research: a tutorial'
author: 
  - name: Andrea Onofri
    affiliation: Department of Agriculture, Food and Environmental Sciences, University of Perugia, Borgo XX Giugno 74, 06121 Perugia, Italy, andrea.onofri@unipg.it
  - name: Hans-Peter Piepho
    affiliation: Biostatistics Unit, Institute of Crop Science, University of Hohenheim, Fruwirthstr. 23, 70593 Stuttgart, Germany, hans-peter.piepho@uni-hohenheim.de
  - name: Marcin Kozak
    affiliation: Department of Botany, Warsaw University of Life Sciences – SGGW, Nowoursynowska 159, 02-776 Warsaw, Poland, nyggus@gmail.com
output: 
  html_document 
---

---

#Introduction

We have recently written a paper titled "Analyzing interval-censored data in agricultural research: a review with examples and code snippets" (*Literature reference, when available*). In that paper we noted that ‘survival analysis’ has mostly been overlooked in agricultural research. This is not because censored data are not found in agriculture. Indeed, a survey of literature in agronomy and related disciplines shows several examples where individual traits cannot be measured with high precision. Their values need to be represented by uncertainty intervals into which the real values fall. Therefore, these measures are censored. Some examples? In the paper we mentioned several of them: e.g. 

1. time-to-event data (flowering times, germination times)
2. measurements taken with instruments with low resolution or an upper/lower limit of detection
3. counts of organisms which are recorded as higher than a certain threshold value
4. visual measurements on a conventional rating scale (e.g. when scoring pesticide efficacy/phytotoxicity, leaf damage, plant growth, disease severity...).

The problem is not that censored data do not exist in agricultural research; the problem is that, dealing with these data, agricultural researchers do not select the appropriate methods of data analysis, but they keep on using the conventional tools, such as ANOVA and regression, which are either wrong or inefficient.

In the paper we gave three examples and try to show why it is important to use methods that fully respect the manner in which the data were collected. We also gave some software tips to make censored data methods slightly more popular among biologists/agricultural scientists. However, we are very thankful to the reviewers, who suggested that we probably needed some extra space, to take the readers hand-by-hand and guide them through the process of data analysis with censored data.

This webpage aims at providing fully commented R code and the datasets to reproduce all the analysis and results in our main paper. Our hope is that, whenever censored data are recognised, the correct techniques are used more extensively. Please, use the top menu to get access to the different sections of this site.

#The package

This web site is associated to an R package, that contains all the dataset. Please, install this package from gitHub. If you have not done this before, you also need to install the *devtools* package. The code is as follows:

```{r}
# install.packages("devtools")
library(devtools)
install_github("OnofriAndreaPG/agriCensData")
```




